garnet: Remove duplicate media.c2
getDeviceHalManifest: -2147483648 VINTF parse error: Cannot add manifest fragment /vendor/etc/vintf/manifest/c2_manifest_vendor.xml: HAL "android.hardware.media.c2" has a conflict: Conflicting FqInstance: @1.0::IComponentStore/default (from /vendor/etc/vintf/manifest.xml) vs. @1.0::IComponentStore/default (from /vendor/etc/vintf/manifest/c2_manifest_vendor.xml). Check whether or not multiple modules providing the same HAL are installed.
Unable to print HALs from new FCMs: no device HAL manifest.
ERROR: No such device: No device manifest file from device or from update package
No device manifest.
No device HAL manifest
Missing device manifest.: No such file or directory: No such device

Signed-off-by: Sensei <senseidev24@gmail.com>